ititle: Ewa Siekierzyńska
logo: /assets/img/f_prt_2.png
description:
    email:ewa.siekierzynska@gmail.com
    <br><br>
    linkedin:https://www.linkedin.com/in/ewa-siekierzyńska
show_downloads: false
theme: jekyll-theme-minimal
minimal:
  show_repo_link: false
  show_downloads: false
  show_project_tagline: true
  search: false
  skin: auto
plugins:
  - jekyll-feed
include: ["assets/css"]
classes: wide
