title: Ewa Siekierzyńska
--logo: /assets/img/headshot_circle.png
logo: /assets/img/f_prt_2.png
description: 
    <br><br>  
    Email: ewa.siekierzynska@gmail.com
    <br><br>  
    Phone: (936) 537 0533
  <br><br>
  <a href="https://www.linkedin.com/in/ewa-siekierzyńska">View LinkedIn Profile</a>  



show_downloads: false
theme: jekyll-theme-minimal
minimal:
  show_repo_link: false
  show_downloads: false
  search: false
  skin: auto
plugins:
  - jekyll-feed
include: ["assets/css"]
classes: wide
