title: Ewa Siekierzyńska
logo: /assets/img/f_prt_2.png
description:
    Email: ewa.siekierzynska@gmail.com
    <br><br>
    <a href="https://www.linkedin.com/in/ewa-siekierzyńska">LinkedIn Profile</a>
show_downloads: false
theme: jekyll-theme-minimal
minimal:
  show_repo_link: true
  show_downloads: false
  show_project_tagline: true
  show_project_email: true
  search: false
  skin: auto
plugins:
  - jekyll-feed
include: ["assets/css"]
classes: wide
