title: Ewa portfolio
--logo: /assets/img/headshot_circle.png
logo: /assets/img/f_prt_2.png
#description: my curriculum vitae
show_downloads: false
theme: jekyll-theme-minimal
minimal:
  show_repo_link: false
markdown: kramdown
plugins:
  - jekyll-feed
include: ["assets/css"]
classes: wide


